name: Deploy project
on: push
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout
      - name: Install nodejs
        uses: actions/setup-node
        with:
          node-version: 20
      - name: Install dependencies
        run: npm ci
      - name: Check lint
        run: npm run lint
  build:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout
      - name: Install nodejs
        uses: actions/setup-node
        with:
          node-version: 20
      - name: Install dependencies
        run: npm ci
      - name: Build script
        run: npm run build
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout
      - name: Install nodejs
        uses: actions/setup-node
        with:
          node-version: 20
      - name: Install dependencies
        run: npm ci
      - name: Deploy code
        run: echo "Deploying to cloud ..."
